### ISSUE TITLE
Support for `$` in Comments

### ISSUE THREAD

**Issue by swolfand** [Microsoft/thrifty#138]
If a comment in a thrift file has a `$` in it, JavaPoet will get confused and crash. 

Input:  

```
namespace java com.example.bug

# A comment with symbols: $
enum BogusEnum {
  # A bogus value
  VALUE = 0
}

struct TestStruct {
  1: optional string thing
}
```

When running this through the thrifty-compiler, it will crash with 

```
Unhandled exception:
java.lang.IllegalArgumentException: index 1 for '$
' not in range (received 0 arguments)
	at com.squareup.javapoet.Util.checkArgument(Util.java:64)
	at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:232)
	at com.squareup.javapoet.TypeSpec$Builder.addJavadoc(TypeSpec.java:390)
	at com.microsoft.thrifty.gen.ThriftyCodeGenerator.buildEnum(ThriftyCodeGenerator.java:1121)
	at com.microsoft.thrifty.gen.ThriftyCodeGenerator.generateTypes(ThriftyCodeGenerator.java:204)
	at com.microsoft.thrifty.gen.ThriftyCodeGenerator.generate(ThriftyCodeGenerator.java:274)
	at com.microsoft.thrifty.gen.ThriftyCodeGenerator.generate(ThriftyCodeGenerator.java:177)
	at com.microsoft.thrifty.compiler.ThriftyCompiler.compile(ThriftyCompiler.java:217)
	at com.microsoft.thrifty.compiler.ThriftyCompiler.main(ThriftyCompiler.java:96)
```

**Comment by benjamin-bader** [comment]
TIL that `addJavadoc`'s first arg is a format string, not a literal.  Good catch!
