### ISSUE TITLE
Error: java.net.SocketException: Protocol wrong type for socket

### ISSUE THREAD

**Issue by ajribeiro** [Microsoft/thrifty#146]
I followed the instructions on the readme, but I am running into the above error.  My code looks like:
```
        // Transports define how bytes move to and from their destination
        SocketTransport transport = new SocketTransport.Builder("localhost", XPC_PORT)
                .readTimeout(XPC_TIMEOUT)
                .connectTimeout(XPC_TIMEOUT)
                .build();
        try {
            transport.connect();
            System.out.println(transport.isConnected());
        } catch (IOException e) {
            System.out.println("connection error");
            e.printStackTrace();
            System.exit(-1);
        }

        // Protocols define the mapping between structs and bytes
        Protocol protocol = new BinaryProtocol(transport);
        // Generated clients do the plumbing
        XPC xpcClient = new XPCClient(protocol, new ClientBase.Listener() {
            @Override
            public void onTransportClosed() {
                System.out.println("listener closed");
            }

            @Override
            public void onError(Throwable error) {
                System.out.println("listener error");
                error.printStackTrace();
                System.exit(-1);
            }
        });

        System.out.println("client up");

        // RPC clients are asynchronous and callback-based
        xpcClient.uploadTrackedExperiments(
                requestUploadTrackedExperiments,
                new ServiceMethodCallback<ResponseUploadTrackedExperiments>() {
                    @Override
                    public void onSuccess(ResponseUploadTrackedExperiments response) {
                        System.err.println("SUCCESS");
                        System.err.println(response);
                    }
                    @Override
                    public void onError(Throwable error) {
                        System.err.println("ERROR");
                        error.printStackTrace();
                    }
        });
```

and the corresponding output is:

```
creating transport
true
client up
listener error
java.net.SocketException: Protocol wrong type for socket
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at com.microsoft.thrifty.transport.SocketTransport.write(SocketTransport.java:113)
	at com.microsoft.thrifty.protocol.BinaryProtocol.writeI32(BinaryProtocol.java:176)
	at com.uber.experimentation.xpc.RequestUploadTrackedExperiments$RequestUploadTrackedExperimentsAdapter.write(RequestUploadTrackedExperiments.java:178)
	at com.uber.experimentation.xpc.RequestUploadTrackedExperiments$RequestUploadTrackedExperimentsAdapter.write(RequestUploadTrackedExperiments.java:147)
	at com.uber.experimentation.xpc.XPCClient$UploadTrackedExperimentsCall.send(XPCClient.java:805)
	at com.microsoft.thrifty.service.ClientBase$WorkerThread.invokeRequest(ClientBase.java:223)
	at com.microsoft.thrifty.service.ClientBase$WorkerThread.run(ClientBase.java:192)
```

As far as I can tell, thrifty doesn't have that many options for thrift Protocol.  Any help would be appreciated.

**Comment by benjamin-bader** [comment]
That's intriguing, but definitely isn't a Thrifty error.  That message seems to be a POSIX error message whose origin is unclear to me.

This seems to be the default message associated with `EPROTOTYPE`, which is what is returned by the kernel when it can't handle a certain network protocol.  Just about everything speaks TCP, and your logs show that your socket is locally connected, so I don't think that your kernel doesn't know TCP.

Unfortunately, it's not possible for me to know what's actually happening in your system :(

**Comment by ajribeiro** [comment]
Thanks for the quick reply.  I'm on a Mac, running Sierra, 10.12.4

**Comment by benjamin-bader** [comment]
Same here, which means that I'm afraid I don't know how to help :(

FYI, we use basically the same code in our [integration tests][1], without any similar issue.  Can you reproduce this error reliably?   If so, can you share code for a test case that reliably fails this way?

[1]: https://github.com/Microsoft/thrifty/blob/master/thrifty-integration-tests/src/test/java/com/microsoft/thrifty/integration/conformance/ConformanceBase.java#L87

**Comment by ajribeiro** [comment]
Whats interesting is that the error is intermittent.  In consecutive runs, I got the above error, in addition to:

```
java.io.EOFException: Expected 4 bytes; got 0
	at com.microsoft.thrifty.protocol.BinaryProtocol.readFully(BinaryProtocol.java:382)
	at com.microsoft.thrifty.protocol.BinaryProtocol.readI32(BinaryProtocol.java:322)
	at com.microsoft.thrifty.protocol.BinaryProtocol.readMessageBegin(BinaryProtocol.java:219)
	at com.microsoft.thrifty.service.ClientBase$WorkerThread.invokeRequest(ClientBase.java:233)
	at com.microsoft.thrifty.service.ClientBase$WorkerThread.run(ClientBase.java:192)
```

and

```
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at com.microsoft.thrifty.transport.SocketTransport.write(SocketTransport.java:113)
	at com.microsoft.thrifty.protocol.BinaryProtocol.writeI32(BinaryProtocol.java:176)
	at com.microsoft.thrifty.protocol.BinaryProtocol.writeListBegin(BinaryProtocol.java:132)
	at com.uber.experimentation.xpc.BuildInfo$BuildInfoAdapter.write(BuildInfo.java:534)
	at com.uber.experimentation.xpc.BuildInfo$BuildInfoAdapter.write(BuildInfo.java:459)
	at com.uber.experimentation.xpc.RequestUploadTrackedExperiments$RequestUploadTrackedExperimentsAdapter.write(RequestUploadTrackedExperiments.java:163)
	at com.uber.experimentation.xpc.RequestUploadTrackedExperiments$RequestUploadTrackedExperimentsAdapter.write(RequestUploadTrackedExperiments.java:147)
	at com.uber.experimentation.xpc.XPCClient$UploadTrackedExperimentsCall.send(XPCClient.java:805)
	at com.microsoft.thrifty.service.ClientBase$WorkerThread.invokeRequest(ClientBase.java:223)
	at com.microsoft.thrifty.service.ClientBase$WorkerThread.run(ClientBase.java:192)
```

I'll see if i can get a small snippet to repro

**Comment by benjamin-bader** [comment]
How odd!  Those both sound like the server dropping the connection.  We use `BinaryProtocol` heavily in Outlook, but I won't rule out a bug in message decoding.

The absolute best data for me to help is to see the actual bytes on the wire, before being passed to a `Protocol` object.  The last time I saw a bug like this, this is how I figured it out.  Turned out that the user was on a captive wifi portal that was naively trying to send an HTTP redirect to their login flow - what a surprise, for a Thrift struct to start with `HTTP`!

Unfortunately, this is not built in to Thrifty, and requires a bit of `Transport` surgery.  You could use the following (untested) transport decorator to do it:

```java
class VCRTransport extends Transport {
    public final Buffer bytesRead = new Buffer();
    public final Buffer bytesWritten = new Buffer();
    
    private final Transport delegate;

    VCRTransport(Transport delegate) {
        this.delegate = delegate;
    }

    public void rewind() {
        bytesRead.clear();
        bytesWritten.clear();
    }

    @Override
    public int read(byte[] buffer, int offset, int count) throws IOException {
        int bytesRead = delegate.read(buffer, offset, count);
        if (bytesRead > 0) {
            this.bytesRead.write(buffer, offset, bytesRead);
        }
        return bytesRead;
    }

    @Override
    public void write(byte[] buffer, int offset, int count) throws IOException {
        this.bytesWritten.write(buffer, offset, count);
        delegate.write(buffer, offset, count);
    }

    @Override
    public void flush() throws IOException {
        delegate.flush();
    }

    @Override
    public void close() throws IOException {
        delegate.close();
    }
}

// later on
SocketTransport st = ...;
VCRTransport vcr = new VCRTransport(st);
BinaryProtocol protocol = new BinaryProtocol(vcr);

// continue as normal
```

When the error happens, the two buffers should have a history of everything read from/written to the underlying transport, and will help guide your investigation.  If there's a bug in our BinaryProtocol implementation, the recorded data will be super helpful in figuring out where it is.

**Comment by benjamin-bader** [comment]
For posterity:
@ajribeiro and I talked it over offline.  The problem was that the server was expecting non-thrift wire format (tchannel) whose _payload_, when re-assembled, would be binary-encoded thrift.  Thrifty doesn't implement tchannel, but it's conceivable that we could someday implement a parser and code generator for tchannel IDL.

In the meantime, thrifty is working as intended.
