### ISSUE TITLE
Java code generation fails for thrift schema with namespace *

### ISSUE THREAD

**Issue by timvlaer** [microsoft/thrifty#325]
Code generation fails for following schema:
```
namespace * thrift.test

enum Numberz
{
  ONE = 1,
}
```
with the following exception. 
```
java.lang.NullPointerException
	at com.squareup.javapoet.ClassName.<init>(ClassName.java:59)
	at com.squareup.javapoet.ClassName.<init>(ClassName.java:48)
	at com.squareup.javapoet.ClassName.get(ClassName.java:198)
	at com.microsoft.thrifty.gen.ThriftyCodeGenerator.buildEnum(ThriftyCodeGenerator.kt:982)
	at com.microsoft.thrifty.gen.ThriftyCodeGenerator.generateTypes(ThriftyCodeGenerator.kt:149)
	at com.microsoft.thrifty.gen.ThriftyCodeGenerator.generate(ThriftyCodeGenerator.kt:170)
	at com.microsoft.thrifty.gen.ThriftyCodeGenerator.generate(ThriftyCodeGenerator.kt:131)
	at com.microsoft.thrifty.compiler.ThriftyCompiler$cli$1.generateJava(ThriftyCompiler.kt:323)
	
```
Looks like the all namespace is not supported?

**Comment by benjamin-bader** [comment]
Uh oh!  I can confirm that I have never tested this case as we don't use the wildcard namespace.  Good catch!
