### ISSUE TITLE
Deprecated Gradle APIs in use, will break in Gradle 8

### ISSUE THREAD

**Issue by benjamin-bader** [microsoft/thrifty#479]
They all appear to be from Dokka, as documented in [this issue from 2021](https://github.com/Kotlin/dokka/issues/1833).

This issue is just a reminder to come back and look at this in advance of Gradle 8.

**Comment by benjamin-bader** [comment]
Well, turns out it's not Dokka, it's _Kotlin_.  Even as of 1.7.20, with Gradle 8.0 builds coming thick and fast, these still haven't been fixed:

```
~/D/thrifty ❯❯❯ ./gradlew -s clean check --warning-mode all                                                                                                                            ✘ 1
The TestReport.destinationDir property has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the destinationDirectory property instead. See https://docs.gradle.org/7.6/dsl/org.gradle.api.tasks.testing.TestReport.html#org.gradle.api.tasks.testing.TestReport:destinationDir for more details.
        at org.gradle.api.tasks.testing.TestReport.setDestinationDir(TestReport.java:92)
        at org.jetbrains.kotlin.gradle.testing.internal.KotlinTestReport_Decorated.setDestinationDir(Unknown Source)
        at org.jetbrains.kotlin.gradle.testing.internal.KotlinTestsRegistry$doGetOrCreateAggregatedTestTask$aggregate$1.invoke(KotlinTestsRegistry.kt:74)
        at org.jetbrains.kotlin.gradle.testing.internal.KotlinTestsRegistry$doGetOrCreateAggregatedTestTask$aggregate$1.invoke(KotlinTestsRegistry.kt:70)
        at org.jetbrains.kotlin.gradle.tasks.TasksProviderKt$sam$org_gradle_api_Action$0.execute(TasksProvider.kt)
```

Not really sure what we can do other than eat popcorn and watch the show, waiting for JetBrains to fix their stuff.
