### ISSUE TITLE
Compilation breaks for IDLs with use includes with relative paths

### ISSUE THREAD

**Issue by stefanodacchille** [Microsoft/thrifty#5]
# Observed Behaviour

The thrifty compiler fails when a Thrift IDL file declares includes using relative paths. So for example: there is a file `Foo.thrift` in the `foo` folder that depends on another file `Bar.thrift` in the `bar` folder and it declares the dependency like this: `include ../bar/Bar.thrift`. When running `java -jar thrifty-compiler-0.2.0.jar ./foo/Foo.thrift ./bar/Bar.thrift` the compiler will fail with the following exception:
```
Exception in thread "main" java.lang.AssertionError: All includes should have been resolved by now: /some/absolute/path/foo/../bar/Bar.thrift
	at com.microsoft.thrifty.schema.Loader.getAndCheck(Loader.java:274)
	at com.microsoft.thrifty.schema.Loader.resolveIncludedProgram(Loader.java:232)
	at com.microsoft.thrifty.schema.Program.loadIncludedPrograms(Program.java:232)
	at com.microsoft.thrifty.schema.Loader.loadFromDisk(Loader.java:145)
	at com.microsoft.thrifty.schema.Loader.load(Loader.java:107)
	at com.microsoft.thrifty.compiler.ThriftyCompiler.compile(ThriftyCompiler.java:178)
	at com.microsoft.thrifty.compiler.ThriftyCompiler.main(ThriftyCompiler.java:93)
```

# Cause

The `loadFromDisk` method in the `Loader` class stores `Program`s using their canonical paths but `getAndCheck` is invoked using the absolute path built by the `findFirstExisting` method, which creates a file using parent and file paths when resolving paths according to the current location or include paths rules.

# Fix

Invoking the `getAndCheck` using canonical paths instead of absolute ones.

**Comment by benjamin-bader** [comment]
Yikes!  Good catch.
